import { type AISummaryResponse } from '../../types/api';
import { Badge } from '../ui/Badge';

interface AISummaryCardProps {
  summary: AISummaryResponse;
}

const priorityVariant: Record<string, 'error' | 'warning' | 'info'> = {
  HIGH: 'error',
  MEDIUM: 'warning',
  LOW: 'info',
};

export function AISummaryCard({ summary }: AISummaryCardProps) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
      {/* Executive Summary */}
      <div style={{ padding: 20, background: '#eff6ff', borderRadius: 12, border: '1px solid #bfdbfe' }}>
        <div style={{ fontWeight: 700, color: '#1e40af', marginBottom: 8 }}>Executive Summary</div>
        <p style={{ margin: 0, color: '#1e3a8a', lineHeight: 1.6 }}>{summary.summaryText}</p>
      </div>

      {/* Top Issues */}
      <div>
        <h4 style={{ margin: '0 0 12px', color: '#111827' }}>Top Issues</h4>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {summary.topIssues.map((issue, i) => (
            <div key={i} style={{
              display: 'flex',
              alignItems: 'center',
              gap: 12,
              padding: '12px 16px',
              background: 'white',
              borderRadius: 8,
              border: '1px solid #e5e7eb',
            }}>
              <div style={{
                width: 28,
                height: 28,
                borderRadius: '50%',
                background: '#f3f4f6',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontWeight: 700,
                fontSize: '0.85rem',
                color: '#374151',
                flexShrink: 0,
              }}>
                {i + 1}
              </div>
              <div style={{ flex: 1 }}>
                <div style={{ fontWeight: 600, color: '#111827' }}>{issue.description}</div>
                <div style={{ fontSize: '0.8rem', color: '#6b7280', marginTop: 2 }}>
                  Code: <code>{issue.errorCode}</code>
                </div>
              </div>
              <div style={{ textAlign: 'right', flexShrink: 0 }}>
                <div style={{ fontWeight: 700, color: '#dc2626' }}>{issue.count.toLocaleString()}</div>
                <div style={{ fontSize: '0.75rem', color: '#9ca3af' }}>{issue.percentage.toFixed(1)}%</div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Recommendations */}
      <div>
        <h4 style={{ margin: '0 0 12px', color: '#111827' }}>Recommendations</h4>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {summary.recommendations.map((rec, i) => (
            <div key={i} style={{
              display: 'flex',
              gap: 12,
              alignItems: 'flex-start',
              padding: '12px 16px',
              background: 'white',
              borderRadius: 8,
              border: '1px solid #e5e7eb',
            }}>
              <Badge variant={priorityVariant[rec.priority] ?? 'neutral'}>{rec.priority}</Badge>
              <span style={{ color: '#374151', lineHeight: 1.5 }}>{rec.message}</span>
            </div>
          ))}
        </div>
      </div>

      <div style={{ fontSize: '0.75rem', color: '#9ca3af', textAlign: 'right' }}>
        Generated by Claude AI · {new Date(summary.generatedAt).toLocaleString()}
      </div>
    </div>
  );
}
