import { useParams, useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { getAISummary } from '../api/ai.api';
import { AISummaryCard } from '../components/insights/AISummaryCard';
import { Spinner } from '../components/ui/Spinner';
import { ErrorAlert } from '../components/ui/ErrorAlert';

export function AIInsightsPage() {
  const { jobId } = useParams<{ jobId: string }>();
  const navigate = useNavigate();

  const { data, isLoading, error, refetch } = useQuery({
    queryKey: ['aiSummary', jobId],
    queryFn: () => getAISummary(jobId!),
    enabled: !!jobId,
    retry: false,
  });

  return (
    <div style={{ maxWidth: 800, margin: '0 auto', padding: '40px 24px' }}>
      <div style={{ background: 'white', borderRadius: 16, padding: 32, boxShadow: '0 1px 3px rgba(0,0,0,0.1)', border: '1px solid #e5e7eb' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
          <div>
            <h2 style={{ margin: '0 0 4px', color: '#111827' }}>AI Validation Insights</h2>
            <div style={{ fontSize: '0.8rem', color: '#6b7280', display: 'flex', alignItems: 'center', gap: 4 }}>
              ✨ Generated by Claude AI
            </div>
          </div>
          <button
            onClick={() => navigate(`/download/${jobId}`)}
            style={{ background: '#16a34a', color: 'white', border: 'none', borderRadius: 8, padding: '8px 18px', fontWeight: 600, cursor: 'pointer' }}
          >
            ⬇ Download
          </button>
        </div>

        {isLoading && (
          <div style={{ textAlign: 'center', padding: 48 }}>
            <Spinner size={40} />
            <div style={{ marginTop: 16, color: '#6b7280' }}>Claude is analyzing your validation results…</div>
          </div>
        )}

        {error && (
          <ErrorAlert
            message={(error as Error).message}
            onDismiss={() => refetch()}
          />
        )}

        {data && <AISummaryCard summary={data} />}
      </div>
    </div>
  );
}
